datasources {
  default {
    driverClassName = "org.postgresql.Driver"
    url = "${POSTGRES_URL}"
    username = "${POSTGRES_USER}"
    password = "${POSTGRES_PASSWORD}"
    dialect = POSTGRES
    maximum-pool-size = 5
  }
}
liquibase {
  datasources {
    default {
      change-log: "classpath:db/liquibase-changelog.xml"
    }
  }
}
micronaut {
  application {
    name = verotel
  }
  server {
    port = "${PORT:5000}"
    default-charset = "UTF-8"
  }
}
